In [1]:
# les packages necessaires
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('train.csv')
df.head()


ID  score_1  offensive rebound_1  defensive rebound_1  offensive foul_1  \
0  14186       -2                    0                    0                 0   
1  13013        0                    0                   -1                 0   
2   7102        0                    0                    0                 0   
3   7637       -2                    0                    0                 0   
4  12350        0                    0                    0                 0   

   defensive foul_1  assist_1  lost ball_1  steals_1  bad pass_1    ...      \
0                 0         0            0         0           0    ...       
1                 0         0            0         0           0    ...       
2                 0         0            0         1           1    ...       
3                 0         0            0         0           0    ...       
4                 0         0            0         0           0    ...       

   offensive rebound_1440  defensive rebound_1440  offensive foul_1440  \
0                       8                      -4                    2   
1                       1                       5                    0   
2                      -1                      -5                   -5   
3                       2                       8                    1   
4                       4                       1                    0   

   defensive foul_1440  assist_1440  lost ball_1440  steals_1440  \
0                    0           -3               3            3   
1                    0            1               0            0   
2                    0            0               5            5   
3                    0           -1              -1            2   
4                    0            4               3            2   

   bad pass_1440  block_1440  miss_1440  
0             -2           1          9  
1              1          -2         -1  
2             -2           3         -5  
3              2          -1         -1  
4              1           1          3  

[5 rows x 15841 columns]

In [3]:
# we will try to learn from the last second
X = df.values
X = X[:,15830:15841]
print(X)

[[-13   8  -4 ...  -2   1   9]
 [ -5   1   5 ...   1  -2  -1]
 [  5  -1  -5 ...  -2   3  -5]
 ...
 [ -9  -2  -1 ...  -1   2  -3]
 [  6  -3  -2 ...   2   3  -4]
 [-18   8  -6 ...   2   3  11]]


In [4]:
dfy = pd.read_csv('challenge_output_data_training_file_nba_challenge.csv',sep=';')
Y = dfy.values
Y = Y[:,1]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)

In [12]:
# Using Decision Tree
from sklearn.tree import DecisionTreeClassifier
oneTree = DecisionTreeClassifier(max_depth = 4)
oneTree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [13]:
print(accuracy_score(Y_train,oneTree.predict(X_train)))

0.7228628230616302


In [14]:
predictions = oneTree.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,predictions))

0.7261526232114467


In [17]:
# Learning decision tree on the whole data set
oneTreeAll = DecisionTreeClassifier(max_depth = 4)
oneTreeAll.fit(X,Y)
dfTest = pd.read_csv('test.csv')
X_Test_All = dfTest.values
X_Test_All = X_Test_All[:,15830:15841]
Y_pred_test = oneTreeAll.predict(X_Test_All)
print(Y_pred_test)

[1 0 0 ... 1 0 1]


In [18]:
X_entier = dfTest.values
Y_essai = np.array([X_entier[:,0],Y_pred_test])
Y_essai = Y_essai.T
np.savetxt('essaiUneSecondeDecisionTree.csv', Y_essai, delimiter=';',fmt='%i', header="ID;label")

In [16]:
# Performance modele regression logistique
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression(C=0.01)
logReg.fit(X,Y)

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [17]:
print (logReg.score(X,Y))

0.7229643765903307


In [10]:
Y_pred_test = logReg.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred_test))

0.724960254372019


In [20]:
dfTest = pd.read_csv('test.csv')

In [21]:

X_Test = dfTest.values
X_Test = X_Test[:,15830:15841]

In [22]:

Y_pred_test = logReg.predict(X_Test)


In [23]:
X_entier = dfTest.values
Y_essai = np.array([X_entier[:,0],Y_pred_test])

In [24]:
Y_essai = Y_essai.T

In [25]:
print(Y_essai)

[[  781     1]
 [  914     0]
 [12795     0]
 ...
 [11199     1]
 [17432     0]
 [ 4234     1]]


In [26]:
np.savetxt('essaiUneSeconde.csv', Y_essai, delimiter=';',fmt='%i', header="ID;label")