In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

On charge nos données d'entrainement pour les 30 derniers secondes

In [84]:
X = np.load("MatriceTrainDerniere30Seconds.npy")


On charge nos données test pour les 30 derniers secondes

In [85]:
X_test = np.load("MatriceTestDerniere30Seconds.npy")

In [86]:
Id_test= np.load("IdTest.npy")
print Id_test

[  781   914 12795 ... 11199 17432  4234]


On charge le fichier de sortie, et recupérer notre label à prédire grace à LabelEncoder de sklearn.preprocessing

In [87]:
dfy = pd.read_csv("challenge_output_data_training_file_nba_challenge.csv",sep=';')
le = LabelEncoder() 
Y = le.fit_transform(dfy['label'].values)

The history saving thread hit an unexpected error (OperationalError('disk I/O error',)).History will not be written to the database.


On sépare le jeu de donnéees en trainig set et testing set

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.20)

In [89]:
#créer le classifieur GaussianNb
from sklearn.naive_bayes import GaussianNB
#creer le classifier BernouilliNb
from sklearn.naive_bayes import BernoulliNB


In [90]:
gnb =  GaussianNB(priors=None)
#entrainer le mdéle
gnb.fit(X_train, Y_train)
#prédire l'outpout
ypred_1 = gnb.predict(X_test)

In [92]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

 On évalue les prédictions pour le classifieur GaussianNB

In [93]:
#évaluer les prédiCtions
accuracy = accuracy_score(Y_test, ypred_1, normalize = True)
print('GaussianNB accuracy score: {}'.format(accuracy))

GaussianNB accuracy score: 0.710651828299


In [96]:
gnb =  GaussianNB(priors=None)
#entrainer le mdéle
gnb.fit(X_train, Y_train)
X_test = np.load("MatriceTestDerniere30Seconds.npy")
#prédire l'outpout
ypred_1 = gnb.predict(X_test)
print "Predicted Value:",ypred_1

Predicted Value: [1 0 0 ... 1 0 1]


In [68]:
print(confusion_matrix(Y_test,ypred_1))

[[982 406]
 [313 815]]


In [69]:
bnb = BernoulliNB(alpha=1,binarize=True,class_prior=None, fit_prior=True)
#entrainer le modéle
bnb.fit(X_train, Y_train)
#prédirel'outpout
ypred_2 = bnb.predict(X_test)

    On évalue les prédictions pour notre classifieur BernouilliB

In [71]:
#évaluer les prédictions
accuracy = accuracy_score(Y_test, ypred_2, normalize = True)
print('BernoulliNB accuracy score: {}'.format(accuracy))

BernoulliNB accuracy score: 0.717408585056


In [97]:
bnb = BernoulliNB(alpha=1,binarize=True,class_prior=None, fit_prior=True)
#entrainer le modéle
bnb.fit(X_train, Y_train)
X_test = np.load("MatriceTestDerniere30Seconds.npy")
#prédirel'outpout
ypred_2 = bnb.predict(X_test)

In [107]:
print "Predicted Value:",ypred_2

Predicted Value: [1 0 0 ... 1 0 1]


In [99]:
#Validation croisée
from sklearn.cross_validation import cross_val_score
xval = cross_val_score(bnb, X, Y, cv=5)
print xval

[0.71104928 0.70508744 0.70298211 0.70775348 0.70206842]


In [100]:
#Validation croisée
from sklearn.cross_validation import cross_val_score
xval = cross_val_score(gnb, X, Y, cv=5)
print xval

[0.71224165 0.70389507 0.70298211 0.70059642 0.69291965]


In [101]:
Y_essai1 = np.array([Id_test,ypred_1])
Y_essai1 = Y_essai1.T
print(Y_essai1)

[[  781     1]
 [  914     0]
 [12795     0]
 ...
 [11199     1]
 [17432     0]
 [ 4234     1]]


In [102]:
ypred_1.shape

(4192L,)

In [103]:
np.savetxt('E:\essaiDerniersecondeBayesGaussionNB.csv', Y_essai1 , delimiter =';', fmt = '%s', header ='ID;Label')

In [104]:
Y_essai2 = np.array([Id_test,ypred_2])
Y_essai2 = Y_essai2.T

In [105]:
print Y_essai2

[[  781     1]
 [  914     0]
 [12795     0]
 ...
 [11199     1]
 [17432     0]
 [ 4234     1]]


In [106]:
np.savetxt('E:\essaiDerniersecondeBayesBernoilliNB2.csv', Y_essai2 , delimiter =';', fmt = '%i', header ='ID;Label')